w3ctag/design-principles

- index.bs
This fixes #28, although I'm a little worried that it crams too much advice into a single section.  Thoughts?
> Prefer dictionary to boolean parameters, and other advice related to booleans and dictionaries.

- index.bs
Fixes #34.
This could use some substantive review to see if others agree with this advice, and with how I've described things.
> Describe tradeoffs between live and static objects.

- index.bs
#59 made me realize we could add i18n as well
> Add link to advice on internationalization.

- index.bs
This addresses a part of https://github.com/w3ctag/design-reviews/issues/136 .
This isn't *obviously* a thing that belongs in this document, but I tend to think it may be useful.
> Add links to advice on related topic of specification writing.

- index.bs
> Add advice for event design.

- .travis.yml
This should have much faster boot time, which should be the main time
constraint.  See https://docs.travis-ci.com/user/ci-environment/ .
> Switch to container-based virtualization for Travis CI.

- index.bs
Closes #54. Also performs some autolinking cleanup and avoids three notes in a row.
> Clarify the casing rules a bit more

- index.bs
Fairly simple addition, last section could definitely use some extra eyes.
> Initial draft for #87.

- index.bs
> Polyfills, fixes #84

- index.bs
This was pointed out in review of Web NFC
> Don't invent your own eventlisterner like infra

- index.bs
As noted - this is an initial draft.
> Initial draft for wrapper spec recommendations.

- index.bs
Based on feedback from Domenic on Web NFC and reusing some of his wordings.
> Add info about cancellation

- index.bs
> Minor: Correct number that short mods by

- index.bs
Particularly when considering BigInt vs. Number.
Refs #115
> Some text to warn developers away from doubling up the API surface

- index.bs
> Say more about asynchronous events.

- index.bs
This is by no means intended to be the final submission.
> Attempt at addressing #106.

- index.bs
Taking a stab at addressing #81.
> Better async event advice

- index.bs
> Separate API design parts that are not JavaScript-specific from those that are

- .pr-preview.json
This PR was created using the [helper](https://tobie.github.io/pr-preview/config.html), so we can have the equivalent to w3ctag/security-questionnaire#74 here.
> Add config file for pr-preview.

- index.bs
This depends on tabatkins/bikeshed#1663, which has landed, so it should be good to go.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/183.html" title="Last updated on May 27, 2020, 12:56 AM UTC (0e1dbde)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/183/c5ee760...0e1dbde.html" title="Last updated on May 27, 2020, 12:56 AM UTC (0e1dbde)">Diff</a>
> Change status of the document to ED.

- index.bs
This is a first draft written in 10 minutes during a breakout - quality writing is not something one should be expecting.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/194.html" title="Last updated on May 28, 2020, 9:44 AM UTC (4b28ee7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/194/65aeebf...4b28ee7.html" title="Last updated on May 28, 2020, 9:44 AM UTC (4b28ee7)">Diff</a>
> Add section about optional parameters. Resolves #73.

- index.bs
Cleanup from #194.
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/202.html" title="Last updated on May 28, 2020, 5:39 PM UTC (a1fe750)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/202/af8e2ad...dbaron:a1fe750.html" title="Last updated on May 28, 2020, 5:39 PM UTC (a1fe750)">Diff</a>
> Fix duplicate id.

- index.bs
new section to address https://github.com/w3ctag/design-principles/issues/148
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/189.html" title="Last updated on May 27, 2020, 3:25 PM UTC (a005f40)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/189/c5ee760...a005f40.html" title="Last updated on May 27, 2020, 3:25 PM UTC (a005f40)">Diff</a>
> added section on manifests

- index.bs
An attempt to write a new, more friendly, abstract and also rename the document as discussed in this [week's virtual f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2020/05-distributed/README.md).
This should be reflecting the discussion in:
https://github.com/w3ctag/design-principles/issues/191
The following issue has been closed:
https://github.com/w3ctag/design-principles/issues/153
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/197.html" title="Last updated on May 29, 2020, 1:20 AM UTC (bfd8667)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/197/049ce03...bfd8667.html" title="Last updated on May 29, 2020, 1:20 AM UTC (bfd8667)">Diff</a>
> Changed Name and added expanded Abstract

- index.bs
I wrote this in a breakout with @plinss during our virtual face-to-face.
Fixes #173.
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/198.html#devices-platforms" title="Last updated on May 29, 2020, 2:22 AM UTC (00c2aa3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/198/049ce03...dbaron:00c2aa3.html" title="Last updated on May 29, 2020, 2:22 AM UTC (00c2aa3)">Diff</a>
> Add section on supporting the range of devices and platforms.

- deploy-gh-pages.sh
Should have been part of #200.
> Die on warnings when Travis tries to deploy.

- index.bs
Rename to "Put user needs first", and reword in simpler language.
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/204.html" title="Last updated on May 29, 2020, 12:36 AM UTC (11f85c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/204/850b40c...alice:11f85c9.html" title="Last updated on May 29, 2020, 12:36 AM UTC (11f85c9)">Diff</a>
> Reword the 'priority of constituencies' principle

- style-guide.md
Needs a lot of work, but it's a starting point.
> Add basic style guide

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/219.html" title="Last updated on Jul 19, 2020, 11:50 PM UTC (96cf532)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/219/d0ad23a...alice:96cf532.html" title="Last updated on Jul 19, 2020, 11:50 PM UTC (96cf532)">Diff</a>
> Readability edits: Basic principles section

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/225.html" title="Last updated on Aug 11, 2020, 9:00 AM UTC (1634dd1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/225/d0ad23a...alice:1634dd1.html" title="Last updated on Aug 11, 2020, 9:00 AM UTC (1634dd1)">Diff</a>
> Readability edits: OS and Device Wrapper APIs section

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/220.html" title="Last updated on Sep 9, 2020, 5:56 AM UTC (b0cb8ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/220/d0ad23a...alice:b0cb8ee.html" title="Last updated on Sep 9, 2020, 5:56 AM UTC (b0cb8ee)">Diff</a>
> Readability edits: API Design Across Languages section

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/222.html" title="Last updated on Sep 22, 2020, 8:12 AM UTC (95ef53e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/222/d0ad23a...alice:95ef53e.html" title="Last updated on Sep 22, 2020, 8:12 AM UTC (95ef53e)">Diff</a>
> Readbility edits: JavaScript Language section

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/221.html" title="Last updated on Sep 25, 2020, 12:07 AM UTC (752fade)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/221/d0ad23a...alice:752fade.html" title="Last updated on Sep 25, 2020, 12:07 AM UTC (752fade)">Diff</a>
> Readability edits: Cascading Style Sheets section

- index.bs
Fixes #235.
Note that the Travis-CI build will fail because of a bug in the HTML spec that needs to be fixed. I've reported that in the #whatwg irc channel.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/236.html" title="Last updated on Oct 5, 2020, 4:09 PM UTC (01b9f86)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/236/ac03524...01b9f86.html" title="Last updated on Oct 5, 2020, 4:09 PM UTC (01b9f86)">Diff</a>
> The Internet is for End Users is now RFC8890.

- index.bs
The newly added principle was motivated the [issue #140] and aims to improve web-consistent naming when given a choice.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/217.html" title="Last updated on Oct 5, 2020, 4:30 PM UTC (d2acec2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/217/c831163...d2acec2.html" title="Last updated on Oct 5, 2020, 4:30 PM UTC (d2acec2)">Diff</a>
> Web Consistent Naming Principle (#140)

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/241.html" title="Last updated on Oct 5, 2020, 11:26 PM UTC (2ac3e87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/241/a264592...dbaron:2ac3e87.html" title="Last updated on Oct 5, 2020, 11:26 PM UTC (2ac3e87)">Diff</a>
> Fix bikeshed fatal error (not indented enough to be valid markdown).

- index.bs
Some followup is required here to file bugs on the specs that required these.
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/242.html" title="Last updated on Oct 5, 2020, 11:54 PM UTC (68d5070)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/242/037a6dc...dbaron:68d5070.html" title="Last updated on Oct 5, 2020, 11:54 PM UTC (68d5070)">Diff</a>
> Fix a bunch of bikeshed link errors.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/224.html" title="Last updated on Oct 7, 2020, 5:37 AM UTC (1a7fb74)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/224/d0ad23a...alice:1a7fb74.html" title="Last updated on Oct 7, 2020, 5:37 AM UTC (1a7fb74)">Diff</a>
> Readability edits: Types and Units section

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/226.html" title="Last updated on Oct 7, 2020, 6:04 AM UTC (7627724)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/226/d0ad23a...alice:7627724.html" title="Last updated on Oct 7, 2020, 6:04 AM UTC (7627724)">Diff</a>
> Readability edits: Other API Design Considerations section

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/228.html" title="Last updated on Oct 8, 2020, 5:17 AM UTC (723837b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/228/75aaee6...alice:723837b.html" title="Last updated on Oct 8, 2020, 5:17 AM UTC (723837b)">Diff</a>
> Readability edits: JavaScript API Surface Concerns section

- index.bs
This links to whatwg/html#6053 for the workaround added in #242.
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/250.html" title="Last updated on Oct 12, 2020, 5:22 PM UTC (fe3ebc1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/250/640c19d...dbaron:fe3ebc1.html" title="Last updated on Oct 12, 2020, 5:22 PM UTC (fe3ebc1)">Diff</a>
> Annotate workaround with link to the bug.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/227.html" title="Last updated on Nov 3, 2020, 8:36 AM UTC (9205acb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/227/d0ad23a...alice:9205acb.html" title="Last updated on Nov 3, 2020, 8:36 AM UTC (9205acb)">Diff</a>
> Readability edits: Writing good specifications section

- index.bs
Needs more polish.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/218.html" title="Last updated on Nov 3, 2020, 8:47 AM UTC (44502b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/218/d0ad23a...44502b7.html" title="Last updated on Nov 3, 2020, 8:47 AM UTC (44502b7)">Diff</a>
> When to use synchronous - #145.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/255.html" title="Last updated on Nov 4, 2020, 6:26 AM UTC (7ec8b5e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/255/53f2f9e...alice:7ec8b5e.html" title="Last updated on Nov 4, 2020, 6:26 AM UTC (7ec8b5e)">Diff</a>
> Fix build-breaking indentation issues

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/forforeach/design-principles/pull/260.html" title="Last updated on Nov 24, 2020, 2:39 PM UTC (2c7e172)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/260/f5a116e...forforeach:2c7e172.html" title="Last updated on Nov 24, 2020, 2:39 PM UTC (2c7e172)">Diff</a>
> fix(index): fix small typo

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/tomayac/design-principles/pull/258.html" title="Last updated on Nov 10, 2020, 10:42 AM UTC (d7e3de6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/258/f5a116e...tomayac:d7e3de6.html" title="Last updated on Nov 10, 2020, 10:42 AM UTC (d7e3de6)">Diff</a>
> Correct markup typo

- index.bs
Fixes #171
Co-Authored-By: Sangwhan "fish" Moon sangwhan@iki.fi
***
<a href="https://pr-preview.s3.amazonaws.com/kenchris/design-principles/pull/263.html" title="Last updated on Jan 27, 2021, 1:04 AM UTC (79dbede)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/263/f5a116e...kenchris:79dbede.html" title="Last updated on Jan 27, 2021, 1:04 AM UTC (79dbede)">Diff</a>
> Considerations and pre-cautions when adding new media formats

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/267.html" title="Last updated on Jan 27, 2021, 3:46 AM UTC (13d81e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/267/29adae5...13d81e5.html" title="Last updated on Jan 27, 2021, 3:46 AM UTC (13d81e5)">Diff</a>
> Added blurb for #253.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/264.html" title="Last updated on Jan 27, 2021, 1:12 AM UTC (90efc4f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/264/f5a116e...90efc4f.html" title="Last updated on Jan 27, 2021, 1:12 AM UTC (90efc4f)">Diff</a>
> Added subsection for #156.

- index.bs
I think this addresses the first three of my review comments in
https://github.com/w3ctag/design-principles/pull/221#pullrequestreview-527876471
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/273.html" title="Last updated on Jan 28, 2021, 1:01 AM UTC (0998884)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/273/8d202ab...dbaron:0998884.html" title="Last updated on Jan 28, 2021, 1:01 AM UTC (0998884)">Diff</a>
> Some followups to the readability edits to the CSS section.

- index.bs
This reference was originally added in #151.
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/275.html" title="Last updated on Jan 28, 2021, 1:54 AM UTC (a09e6a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/275/da03e76...dbaron:a09e6a3.html" title="Last updated on Jan 28, 2021, 1:54 AM UTC (a09e6a3)">Diff</a>
> Fix build by changing payment-request reference to something that still exists.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/305.html" title="Last updated on Apr 16, 2021, 9:08 PM UTC (c847df1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/305/8134f7f...c847df1.html" title="Last updated on Apr 16, 2021, 9:08 PM UTC (c847df1)">Diff</a>
> Trim the trailing whitespace introduced in 298466e.

- index.bs
As discussed in 18b.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/313.html" title="Last updated on May 13, 2021, 7:13 PM UTC (65ee986)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/313/1c64d38...65ee986.html" title="Last updated on May 13, 2021, 7:13 PM UTC (65ee986)">Diff</a>
> Add consistency section, closes #285

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/331.html" title="Last updated on Aug 18, 2021, 4:28 PM UTC (fa1995b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/331/7f66605...fa1995b.html" title="Last updated on Aug 18, 2021, 4:28 PM UTC (fa1995b)">Diff</a>
> Fix Bikeshed linking errors

- index.bs
This is my first, rough draft of text that addresses #117.
Ideally it needs more examples, but I figured I'd push the text while I brainstorm these.
A lot of this prose is based on [minutes](https://github.com/w3ctag/meetings/blob/gh-pages/2020/telcons/05-04-minutes.md#high-level-or-low-level-apis---hober-alice-dbaron-atanassov) from a past breakout, so I've invited all four participants of that conversation to review, including TAG alumni @alice & @dbaron.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/291.html" title="Last updated on Jun 21, 2021, 12:11 PM UTC (0f338e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/291/6922690...0f338e9.html" title="Last updated on Jun 21, 2021, 12:11 PM UTC (0f338e9)">Diff</a>
> Add text for low-level vs high-level APIs (related to #117)

- index.bs
We didn't have any mention of crypto, so here it goes: #185.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/310.html" title="Last updated on Sep 15, 2021, 8:05 AM UTC (e4b1c08)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/310/2f553a7...e4b1c08.html" title="Last updated on Sep 15, 2021, 8:05 AM UTC (e4b1c08)">Diff</a>
> Add a new principle for crypto.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/343.html" title="Last updated on Oct 4, 2021, 1:05 PM UTC (752cb3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/343/0bd75b3...752cb3b.html" title="Last updated on Oct 4, 2021, 1:05 PM UTC (752cb3b)">Diff</a>
> Lowercase web platform, inkeeping with WHATWG style guide, fixes #294

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/337.html" title="Last updated on Sep 23, 2021, 9:02 AM UTC (0de0616)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/337/0bd75b3...0de0616.html" title="Last updated on Sep 23, 2021, 9:02 AM UTC (0de0616)">Diff</a>
> added more metadata for TR publication

- index.bs
Resolves #328
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/345.html" title="Last updated on Nov 2, 2021, 9:08 AM UTC (bbf2f9f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/345/07386d3...bbf2f9f.html" title="Last updated on Nov 2, 2021, 9:08 AM UTC (bbf2f9f)">Diff</a>
> Clarify that different functionality should NOT use the same attributes

- index.bs
Based on a comment from @LeaVerou
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/352.html" title="Last updated on Dec 8, 2021, 4:30 PM UTC (0f28b21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/352/a96703c...0f28b21.html" title="Last updated on Dec 8, 2021, 4:30 PM UTC (0f28b21)">Diff</a>
> Reword functionality to user needs

- index.bs
As discussed in #329
Text by @jakearchibald
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/347.html" title="Last updated on Dec 9, 2021, 8:54 AM UTC (8808b38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/347/07386d3...8808b38.html" title="Last updated on Dec 9, 2021, 8:54 AM UTC (8808b38)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/347.html" title="Last updated on Jan 24, 2022, 5:57 PM UTC (aa0d5a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/347/07386d3...aa0d5a5.html" title="Last updated on Jan 24, 2022, 5:57 PM UTC (aa0d5a5)">Diff</a>
> New principle: Avoid introducing new parser-blocking features, fixes #329

- index.bs
There is some discussion [here](https://github.com/w3ctag/design-principles/issues/70#issuecomment-698945275) that is not captured in this PR, but pushing so that we have a branch to iterate on.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/350.html" title="Last updated on Dec 8, 2021, 4:13 PM UTC (c93ea4c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/350/a96703c...c93ea4c.html" title="Last updated on Dec 8, 2021, 4:13 PM UTC (c93ea4c)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/350.html" title="Last updated on Jan 25, 2022, 9:40 AM UTC (8350d37)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/350/a96703c...8350d37.html" title="Last …
> Add guidance for attributes vs methods. Resolves #70.

- index.bs
I wrote some straw man text for discussion.
Fixes #340.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/362.html" title="Last updated on May 2, 2022, 4:44 PM UTC (13cb6eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/362/8388c68...13cb6eb.html" title="Last updated on May 2, 2022, 4:44 PM UTC (13cb6eb)">Diff</a>
> "Leave the web better than you found it" principle. 

- index.bs
Based on F2F discussion.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/364.html" title="Last updated on Mar 24, 2022, 10:58 AM UTC (c9a82d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/364/8388c68...c9a82d8.html" title="Last updated on Mar 24, 2022, 10:58 AM UTC (c9a82d8)">Diff</a>
> Minor editorial changes to native capabilities section.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/elharo/design-principles/pull/374.html" title="Last updated on May 24, 2022, 4:14 PM UTC (cfb13cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/374/025c56e...elharo:cfb13cd.html" title="Last updated on May 24, 2022, 4:14 PM UTC (cfb13cd)">Diff</a>
> grammar nits

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/382.html" title="Last updated on Jul 26, 2022, 9:53 AM UTC (2394736)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/382/06e9a85...2394736.html" title="Last updated on Jul 26, 2022, 9:53 AM UTC (2394736)">Diff</a>
> Fix all the Bikeshed warnings and errors.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/379.html" title="Last updated on Jul 26, 2022, 10:50 AM UTC (64b1f4a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/379/eaf5072...64b1f4a.html" title="Last updated on Jul 26, 2022, 10:50 AM UTC (64b1f4a)">Diff</a>
> First pass at writing #277

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/design-principles/pull/394.html" title="Last updated on Aug 26, 2022, 12:36 PM UTC (a7696ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/394/a6266b8...johannhof:a7696ce.html" title="Last updated on Aug 26, 2022, 12:36 PM UTC (a7696ce)">Diff</a>
> Fix monkey patching link

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/gibson042/design-principles/pull/410.html" title="Last updated on Dec 27, 2022, 5:54 PM UTC (664781b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/410/69b2ff0...gibson042:664781b.html" title="Last updated on Dec 27, 2022, 5:54 PM UTC (664781b)">Diff</a>
> Fix typos and imprecise phrasing

- index.bs
Closes #366
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/416.html" title="Last updated on Feb 8, 2023, 1:09 AM UTC (7514f7e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/416/a35df00...7514f7e.html" title="Last updated on Feb 8, 2023, 1:09 AM UTC (7514f7e)">Diff</a>
> Change guidance about dictionaries to cover all optional arguments

- index.bs
WIP
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/372.html" title="Last updated on Jul 4, 2022, 6:39 PM UTC (33081c2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/372/025c56e...33081c2.html" title="Last updated on Jul 4, 2022, 6:39 PM UTC (33081c2)">Diff</a>
> New principle: on overloading, for #131

- index.bs
Adding a general guidance about serialization for issue #284
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/367.html" title="Last updated on Apr 20, 2023, 1:28 AM UTC (f257a08)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/367/e81cae6...f257a08.html" title="Last updated on Apr 20, 2023, 1:28 AM UTC (f257a08)">Diff</a>
> Guidance about serialization

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/432.html" title="Last updated on Apr 20, 2023, 2:01 AM UTC (5cb7ce9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/432/c74824c...5cb7ce9.html" title="Last updated on Apr 20, 2023, 2:01 AM UTC (5cb7ce9)">Diff</a>
> fix the build

- index.bs
For #397
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/433.html" title="Last updated on Apr 20, 2023, 5:37 AM UTC (2bed2aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/433/1dd4ba6...2bed2aa.html" title="Last updated on Apr 20, 2023, 5:37 AM UTC (2bed2aa)">Diff</a>
> Remove unnecessary bit in heading

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/434.html" title="Last updated on Apr 21, 2023, 2:28 AM UTC (97cf72d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/434/94996e0...97cf72d.html" title="Last updated on Apr 21, 2023, 2:28 AM UTC (97cf72d)">Diff</a>
> Adding principle for client hints, fixes #307

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/440.html" title="Last updated on May 8, 2023, 11:58 PM UTC (f191c04)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/440/0559332...jyasskin:f191c04.html" title="Last updated on May 8, 2023, 11:58 PM UTC (f191c04)">Diff</a>
> Remove trailing whitespace.

- index.bs
Fixes the build.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/449.html" title="Last updated on Aug 1, 2023, 5:18 PM UTC (a55988e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/449/120e6ac...a55988e.html" title="Last updated on Aug 1, 2023, 5:18 PM UTC (a55988e)">Diff</a>
> Use consistent casing for payment-request reference.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/461.html" title="Last updated on Dec 5, 2023, 5:41 PM UTC (d1dde0e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/461/7fe598f...d1dde0e.html" title="Last updated on Dec 5, 2023, 5:41 PM UTC (d1dde0e)">Diff</a>
> Revert #262. Fixes #458.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/462.html" title="Last updated on Jan 24, 2024, 9:16 AM UTC (50c3536)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/462/1eadb6d...50c3536.html" title="Last updated on Jan 24, 2024, 9:16 AM UTC (50c3536)">Diff</a>
> Add Lea as editor.

- .github/workflows/deploy.yml
- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/466.html" title="Last updated on Jan 24, 2024, 9:59 AM UTC (346396d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/466/0a66b86...346396d.html" title="Last updated on Jan 24, 2024, 9:59 AM UTC (346396d)">Diff</a>
> Update references to WebIDL in notes

- index.bs
This might supersede #354 and #174.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/design-principles/pull/469.html" title="Last updated on Jan 24, 2024, 11:41 AM UTC (e3f2ac3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/469/0a66b86...martinthomson:e3f2ac3.html" title="Last updated on Jan 24, 2024, 11:41 AM UTC (e3f2ac3)">Diff</a>
> Add some discussion on adding removing features

- index.bs
Fixes #399
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/465.html" title="Last updated on Jan 25, 2024, 4:14 PM UTC (af490e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/465/c994a23...af490e1.html" title="Last updated on Jan 25, 2024, 4:14 PM UTC (af490e1)">Diff</a>
> Add data minimization principle

- index.bs
Resolves #378.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/471.html" title="Last updated on Jan 25, 2024, 4:26 PM UTC (63d0cf4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/471/c8a5914...63d0cf4.html" title="Last updated on Jan 25, 2024, 4:26 PM UTC (63d0cf4)">Diff</a>
> Add guidance for factory method naming

- index.bs
...not just sometimes
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/design-principles/pull/474.html" title="Last updated on Mar 5, 2024, 8:30 PM UTC (3a919d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/474/c28ea64...martinthomson:3a919d8.html" title="Last updated on Mar 5, 2024, 8:30 PM UTC (3a919d8)">Diff</a>
> Short is often better

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/396.html" title="Last updated on Mar 6, 2024, 8:48 AM UTC (b4edcf1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/396/2aa21c4...b4edcf1.html" title="Last updated on Mar 6, 2024, 8:48 AM UTC (b4edcf1)">Diff</a>
> New principle: Identity on the web

- index.bs
Closes #398
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/470.html" title="Last updated on Mar 6, 2024, 8:18 PM UTC (f6bebfa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/470/c8a5914...f6bebfa.html" title="Last updated on Mar 6, 2024, 8:18 PM UTC (f6bebfa)">Diff</a>
> Add info to 9.1 ("Use care when exposing identifying information about devices") & change link

- index.bs
Editorial
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/492.html" title="Last updated on Apr 22, 2024, 9:09 AM UTC (95041bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/492/d893e1c...95041bf.html" title="Last updated on Apr 22, 2024, 9:09 AM UTC (95041bf)">Diff</a>
> fix link, see #491

- .gitignore
- Makefile
- README.md
A more complete README.
A Makefile that doesn't assume you have bikeshed installed.
A .gitignore that matches.
> Readme and more

- index.bs
> Modify "leave the web better" to add statement addressing 493

- index.bs
This addresses some of the issues in #481
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/519.html" title="Last updated on Dec 4, 2024, 12:35 PM UTC (a534332)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/519/6f3fb06...a534332.html" title="Last updated on Dec 4, 2024, 12:35 PM UTC (a534332)">Diff</a>
> Update Permissions / Powerful APIs (1.4)

- index.bs
Also active voice.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/524.html" title="Last updated on Dec 4, 2024, 11:20 AM UTC (0933cea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/524/fbf6370...0933cea.html" title="Last updated on Dec 4, 2024, 11:20 AM UTC (0933cea)">Diff</a>
> Only use UTF-8 for #322

- index.bs
Closes #391.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/522.html" title="Last updated on Dec 4, 2024, 1:56 PM UTC (136eab8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/522/c4477d4...136eab8.html" title="Last updated on Dec 4, 2024, 1:56 PM UTC (136eab8)">Diff</a>
> Default values should be the common choice

- index.bs
@rhiaro @torgo
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/528.html" title="Last updated on Dec 4, 2024, 2:02 PM UTC (1040056)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/528/2a60543...1040056.html" title="Last updated on Dec 4, 2024, 2:02 PM UTC (1040056)">Diff</a>
> Friendly amendments to #521

- index.bs
Ensuring we have at least one editor on the next TAG.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/541.html" title="Last updated on Dec 13, 2024, 12:02 AM UTC (60c861d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/541/1a74419...jyasskin:60c861d.html" title="Last updated on Dec 13, 2024, 12:02 AM UTC (60c861d)">Diff</a>
> Add Martin and Jeffrey as co-editors; remove Sangwhan.

- Makefile
- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/543.html" title="Last updated on Dec 13, 2024, 5:58 AM UTC (c69cd61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/543/1a74419...jyasskin:c69cd61.html" title="Last updated on Dec 13, 2024, 5:58 AM UTC (c69cd61)">Diff</a>
> Fix the bikeshed warnings.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/552.html" title="Last updated on Feb 6, 2025, 4:41 PM UTC (8c518a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/552/0379b87...8c518a4.html" title="Last updated on Feb 6, 2025, 4:41 PM UTC (8c518a4)">Diff</a>
> Take Lea out of the editors, as her term has sadly ended.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/553.html" title="Last updated on Feb 10, 2025, 5:08 PM UTC (a199f1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/553/ff03ce4...jyasskin:a199f1f.html" title="Last updated on Feb 10, 2025, 5:08 PM UTC (a199f1f)">Diff</a>
> The privacy-considerations document is obsolete. Replace its reference with privacy-principles.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/559.html" title="Last updated on Feb 26, 2025, 3:07 AM UTC (2979bfd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/559/35a531b...jyasskin:2979bfd.html" title="Last updated on Feb 26, 2025, 3:07 AM UTC (2979bfd)">Diff</a>
> Remove unnecessary anchors and link-defaults.

- index.bs
I found that this could read a little better.  This is not a LOT better, but it might be slightly clearer.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/561.html" title="Last updated on Mar 4, 2025, 2:45 PM UTC (7329528)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/561/af2965b...7329528.html" title="Last updated on Mar 4, 2025, 2:45 PM UTC (7329528)">Diff</a>
> Improvements to purposeful names

- index.bs
Someone moved the cheese.
Closes #576.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/design-principles/pull/577.html" title="Last updated on Jun 3, 2025, 12:10 AM UTC (9e43737)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/577/636ff69...martinthomson:9e43737.html" title="Last updated on Jun 3, 2025, 12:10 AM UTC (9e43737)">Diff</a>
> Update link to CDM definition
