- index.bs
Set the default highlight language to js, remove some use of explicit highlight="js", and add markup to annotate the things that are not JS (because they're HTML, WebIDL, or event names).
Note that it would be possible to go in the other direction and use highlight="js" everywhere.  The editing errors resulting from that are a little less serious (no highlight rather than incorrect highlight), perhaps, but it's a decent amount more markup.
> Use bikeshed's syntax highlighting throughout.

- index.bs
> Add section on error types, initially about avoiding DOMError, but with a drop more than that.

- index.bs
In discussion before dinner we realized that the design-principles document didn't point to the promises-guide.  This adds a brief section on when promises may be needed, and then points to the promises guide for more.
> Suggest use of promises, and point to promises-guide.

- index.bs
- Remove me as editor; closes #63.
- Remove redundant "This Version" and "Issue Tracking" links.
> Clean up header metadata

- index.bs
This was originally part of #75, but it seemed worth splitting out both
into a separate section and a separate pull request.
> Add section on new features being detectable.

- index.bs
At the TAG face-to-face in London last week, @timbl raised the concern that the document seem to be claiming that time is not monotonically increasing, when in fact that's basically the characteristic that makes time what it is.
This pull request attempts to improve the wording of the section in question.  I think it incorporated feedback from a few different TAG members during a side conversation or two, but it certainly wasn't vetted by the whole TAG.
> Improve wording around time vs. timestamps being monotonically increasing.

- index.bs
Github's recommended reviewers list is scary.
> First whack at recommendation for "is" prefix.

- index.bs
Add a section about preferring algorithmic steps and state, or other more readable formal concepts that decompose to them more readable formal concepts that decompose to them.
This also expands the section on specification writing advice to include
a substantive section, rather than being only links to other resources.
Fixes #10.
-----
Note that this is a first shot at this, and I'm expecting substantive comments.  I think @domenic and @annevk and @tabatkins might be particularly interested.
> Add a section about preferring algorithmic steps and state, or other more readable formal concepts that decompose to them.

- index.bs
From discussing with @domenic it seems that `WindowEventHandlers` is the desired place to add the event handler attribute for events which target `window`. If so, this seems useful to point out.
> Recommend using WindowEventHandlers.

- index.bs
Only use BigInt where it is really needed! Number is good for existing
use cases, and existing APIs shouldn't "upgrade" to BigInt unless there
is a very strong reason.
Probably not ready to merge yet, as we will need more practical use cases
to emerge in the web platform to see how this comes up. For the same reason,
WebIDL support is not yet landed, and some open questions remain about how
flexible overloading/unions should be, see
https://github.com/heycam/webidl/pull/525#issuecomment-444073662
I'm putting this out for review now just in case an instance comes up in a TAG
review where someone proposes using BigInt in a specification. Please refer to
this PR for the advice I'd give, and better yet, @ me and I'm happy to take a
look as well.
cc @cynthia
> Add guidance for use of BigInt

- index.bs
The long-awaited text on why constructors are good.
> Classes should have constructors whenever possible

- index.bs
Changing a "must" to "should" here, and referencing the current state
of the WeakRefs proposal (multiple implementation support). In my mind,
a typical specification review should go just as if the WeakRefs proposal
did not exist; this isn't a justification to expose GC further.
> Update GC observability with WeakRefs

- index.bs
The WebUSB specification no longer requires that a device explicitly name the origins that can connect to it. A discussion of why this requirement was removed is included in the [Attacking a Device](https://wicg.github.io/webusb/#attacking-a-device) section of the specification.
> Remove out-of-date WebUSB example

- index.bs
This is a very rough draft of changes to add sections on the Web being safe to browse, trusted user interface, and asking users for consent.  It is intended to fix #146, though it's possible I've gone a little bit beyond my remit in that issue.
This contains a bunch of ideas that I think are widely accepted, but also some that are probably less so, and some that could certainly use more research on what users *actually* understand about the web's safety.  (I thought about whether to explicitly call out the desire for research on that, but so far haven't done so.)
I think this will likely need a considerable amount of review and refinement.  I suspect if I kept it on my computer until next week and then looked at it again, I'd want to rewrite most or all of it.  But nevertheless I think …
> Add sections on the Web being safe to browse, trusted user interface, and asking users for consent.

- index.bs
Following up on issue https://github.com/w3ctag/design-principles/issues/108. We are adding prose for the language and character set to be used.
> API naming advise about language and charset feedback in #108

- index.bs
Part of https://github.com/w3ctag/design-principles/projects/1
> Add the Priority of constituencies principle.

- index.bs
Fixes #139.
(As discussed in Breakout A, about 4 hours ago.)
> Say that if it doesn't fit as an attribute, it should be a method.

- index.bs
This adds a somewhat substantive section on CSS to the design principles document.  It's multiple commits that are **meant to be squashed** when landed.
You should be able to [preview this here](https://dbaron.github.io/design-principles/#css) ~at some point soon, though github seems sluggish right now and it's not up yet~.
Fixes #126.
I'd like to solicit review from @tabatkins and @fantasai as well, but I can't actually mark them in reviewers.
I'm sure there's a lot that can be changed/added here -- I'd like to strike a reasonable balance between trying to polish this, and also trying to defer most "also add X" requests to later PRs.
> Add a section on CSS principles. Fixes #126

- Makefile
I cannot for the life of me get used to typing `bikeshed` directly. My fingers keep typing `make` instead.
> Add a Makefile.

- index.bs
Adds three new principles:
* Consider how your API should behave in private browsing mode
* Do not reveal that private browsing mode is engaged
* Do not reveal that assistive technologies are being used
and modifies "New features should be detectable" to point at them.
@torgo and I hashed these out in a breakout session today, and I drafted this based on my notes from that. @torgo, please let me know if this text works for you.
@Alice, I'd especially like your eyes on the AT principle and the AOM example I use in it.
@mnot & @lknik, TAG alumni reviews would be appreciated!
> New principles related to private browsing mode and assistive technologies. Fixes #97.

- index.bs
Fixes #69, #152, and #181.
The diff is a bit bigger than strictly necessary because I added clause line breaks to the `[[#device-ids]]` section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/180.html" title="Last updated on May 28, 2020, 5:21 PM UTC (2ec5b8e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/180/12e38e5...2ec5b8e.html" title="Last updated on May 28, 2020, 5:21 PM UTC (2ec5b8e)">Diff</a>
> Add principles related to device enumeration & tweak the existing device identifier text.

- Makefile
Would have caught #202, for instance.
> Makefile: die on Bikeshed warnings.

- index.bs
Fixes #93.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/199.html" title="Last updated on May 29, 2020, 12:21 AM UTC (8a1979b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/199/850b40c...8a1979b.html" title="Last updated on May 29, 2020, 12:21 AM UTC (8a1979b)">Diff</a>
> Add guidance on when to use which Web IDL string type

- index.bs
While discussing #137 with @kenchris and @atanassov I realized that the existing advice in this section could be misinterpreted.  This clarifies that advice.  (It's not a fix for that issue, though, but it is related.)
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/201.html#feature-detect" title="Last updated on May 28, 2020, 5:34 PM UTC (e11878b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/201/af8e2ad...dbaron:e11878b.html" title="Last updated on May 28, 2020, 5:34 PM UTC (e11878b)">Diff</a>
> Add paragraph about device detection to clarify advice on feature detection

- index.bs
This PR adds text from four sections of the HTML Design Principles doc:
* 1.1 Conformance for Documents and Implementations
* 4.1 Well-Defined Behavior
* 4.2 Avoid Needless Complexity
The text for Avoid Needless Complexity and Handle Errors is mostly unchanged, though I did tweak it a bit and retitled them.
The existing text on writing algorithms covered most of "Well-Defined Behavior".
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/190.html" title="Last updated on May 29, 2020, 12:33 AM UTC (7e98a01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/190/af8e2ad...7e98a01.html" title="Last updated on May 29, 2020, 12:33 AM UTC (7e98a01)">Diff</a>
> add several HTML Design Principles related to interoperability

- .editorconfig
- .gitignore
- .travis.yml
- index.bs
also added .editorconfig to set editor features
cleaned up yaml formatting
***
<a href="https://pr-preview.s3.amazonaws.com/plinss/design-principles/pull/206.html" title="Last updated on May 29, 2020, 2:34 AM UTC (32a99a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/206/9e66738...plinss:32a99a0.html" title="Last updated on May 29, 2020, 2:34 AM UTC (32a99a0)">Diff</a>
> trim trailing whitespace

- index.bs
This was written during a breakout I just had with @atanassov.
Fixes #104.
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/193.html#naming-unsafe" title="Last updated on Jun 3, 2020, 5:12 AM UTC (8b30698)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/193/65aeebf...dbaron:8b30698.html" title="Last updated on Jun 3, 2020, 5:12 AM UTC (8b30698)">Diff</a>
> Add a subsection about using "unsafe" in names.

- index.bs
Fixes #192.
Also fixes a typo we missed in #197, and moves the `<pre class=anchors>` chunk of Bikeshed metadata up to the top, where the rest of the Bikeshed metadata is.
I generated the list of names from the commit log, closed and open PRs, closed and open issues, and the HTML Design Principles acks.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/210.html" title="Last updated on Jun 3, 2020, 9:29 PM UTC (09a8edf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/210/ed1631c...09a8edf.html" title="Last updated on Jun 3, 2020, 9:29 PM UTC (09a8edf)">Diff</a>
> Add an Acknowledgments section.

- index.bs
Otherwise it defaults to css2 and then on *some* installations of bikeshed it fails to find the reference
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/243.html" title="Last updated on Oct 6, 2020, 12:08 AM UTC (d46dafb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/243/470b2a7...dbaron:d46dafb.html" title="Last updated on Oct 6, 2020, 12:08 AM UTC (d46dafb)">Diff</a>
> Force 'line-height' reference to css-inline-3 to fix intermittent link error

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/alice/design-principles/pull/247.html" title="Last updated on Oct 7, 2020, 11:35 PM UTC (0b4600a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/247/9f2b871...alice:0b4600a.html" title="Last updated on Oct 7, 2020, 11:35 PM UTC (0b4600a)">Diff</a>
> Fix indentation and definition issues which broke the build

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/pwnall/design-principles/pull/248.html" title="Last updated on Oct 11, 2020, 9:26 PM UTC (10a7218)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/248/665ca0e...pwnall:10a7218.html" title="Last updated on Oct 11, 2020, 9:26 PM UTC (10a7218)">Diff</a>
> Fix typo in index.bs

- index.bs
This removes the "browsing context" hack that was added in 470b2a77600eef18dc9f9d5a693131bd5ce522ed (part of that commit) in #242, which is no longer needed because the referencing text was removed in 4f5f94c37726cc00fd264fc7fd3a3d1588f1edf0; the underlying issue whatwg/html#5958 still exists.
It removes the `line-height` hack (added in 8ec8a212d874007cb16f1d94aad85d0db36ba650 in #243) that was needed for unknown reasons and is no longer needed.
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/249.html" title="Last updated on Oct 11, 2020, 11:30 PM UTC (022a23d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/249/e701f0a...dbaron:022a23d.html" title="Last updated on Oct 11, 2020, 11:30 PM UTC (022a23d)">Diff</a>
> Remove workarounds for reference issues.

- index.bs
Addresses https://github.com/w3ctag/design-principles/issues/172
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/240.html" title="Last updated on Jan 27, 2021, 1:50 AM UTC (c61c0ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/240/a264592...c61c0ff.html" title="Last updated on Jan 27, 2021, 1:50 AM UTC (c61c0ff)">Diff</a>
> Preserving content visibility by default (#172)

- index.bs
This refines the advice about how computed values should be affected by
inheritance and property dependencies (and restores the focus to the
depending property rather than the depended-on property).  This
addresses the review comment in
https://github.com/w3ctag/design-principles/pull/221/files#r521131297 .
***
<a href="https://pr-preview.s3.amazonaws.com/dbaron/design-principles/pull/274.html" title="Last updated on Jan 28, 2021, 1:38 AM UTC (3927d52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/274/899519a...dbaron:3927d52.html" title="Last updated on Jan 28, 2021, 1:38 AM UTC (3927d52)">Diff</a>
> Refine advice about CSS computed values.

- index.bs
Also cleans up Bikeshed's anchors and link-defaults blocks.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/272.html" title="Last updated on Feb 2, 2021, 12:41 AM UTC (b2eb8a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/272/5703024...b2eb8a6.html" title="Last updated on Feb 2, 2021, 12:41 AM UTC (b2eb8a6)">Diff</a>
> Use Bikeshed syntax for more things. Fixes #48.

- index.bs
Links to Ethical Web Principles from the abstract and section 1 intro, for #282
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/295.html" title="Last updated on Apr 14, 2021, 3:00 PM UTC (71615e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/295/5c87ce8...71615e1.html" title="Last updated on Apr 14, 2021, 3:00 PM UTC (71615e1)">Diff</a>
> Add links to Ethical Web Principles

- index.bs
The build is currently broken for me. This is the error I'm seeing:
```
bikeshed --die-on=warning spec index.bs build/index.html
LINK ERROR: No 'idl' refs found for 'short_name'.
{{WebAppManifest/short_name}}
✘  Did not generate, due to fatal errors
make: *** [build/index.html] Error 2
```
This PR fixes it.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/304.html" title="Last updated on Apr 16, 2021, 8:59 PM UTC (19a5c83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/304/08f3a98...19a5c83.html" title="Last updated on Apr 16, 2021, 8:59 PM UTC (19a5c83)">Diff</a>
> Fix the build.

- index.bs
See https://github.com/w3ctag/design-principles/issues/252
***
<a href="https://pr-preview.s3.amazonaws.com/ylafon/design-principles/pull/287.html" title="Last updated on May 11, 2021, 12:32 AM UTC (50416d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/287/6922690...ylafon:50416d1.html" title="Last updated on May 11, 2021, 12:32 AM UTC (50416d1)">Diff</a>
> HTTP header syntax definition principle

- index.bs
The added recommendation is about the types of static lists to be considered for API design.
Addresses https://github.com/w3ctag/design-principles/issues/50
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/292.html" title="Last updated on May 13, 2021, 12:32 AM UTC (a0b49a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/292/e5aafa3...a0b49a5.html" title="Last updated on May 13, 2021, 12:32 AM UTC (a0b49a5)">Diff</a>
> Add advice about read-only lists

- index.bs
Rename functions->methods (where appropriate) and parameters->arguments.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/312.html" title="Last updated on May 18, 2021, 1:11 AM UTC (f054236)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/312/2f553a7...f054236.html" title="Last updated on May 18, 2021, 1:11 AM UTC (f054236)">Diff</a>
> Make naming consistent about methods and arguments. Resolves #195.

- index.bs
Written in a breakout with @cynthia today.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/321.html" title="Last updated on Jun 7, 2021, 4:19 PM UTC (0932d35)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/321/0e3164c...0932d35.html" title="Last updated on Jun 7, 2021, 4:19 PM UTC (0932d35)">Diff</a>
> Add some text for factory methods vs constructors (resolves #44)

- index.bs
Resolves #281.
I also added an HTML section, since it will be needed for a variety of future principles, even though this particular one could conceivably also go under Naming.
Not sure if I should scope the new section to be more general than just HTML (e.g. "HTML and other markup languages of the Web Platform") or spell out the acronym like the next section title does.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/326.html" title="Last updated on Aug 2, 2021, 4:06 PM UTC (c9cbf71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/326/1a842fa...c9cbf71.html" title="Last updated on Aug 2, 2021, 4:06 PM UTC (c9cbf71)">Diff</a>
> Add HTML section, add attribute re-use subsection

- index.bs
As discussed in https://github.com/w3ctag/design-reviews/issues/628, we want to improve support for BFCache/non-fully active documents, as we noticed that a lot of API specifications do not handle it well/explicitly.
This change adds various guides and things to be aware of related to non-"fully active" documents, including gives various examples. We hope this will help future APIs to handle BFCache/on-"fully active" documents correctly by default.
cc @hober @domenic @fergal
Note that there's another PR for the "Security & Privacy Questionnaire" doc at https://github.com/w3ctag/security-questionnaire/pull/128
***
<a href="https://pr-preview.s3.amazonaws.com/rakina/design-principles/pull/317.html" title="Last updated on Aug 16, 2021, 10:03 AM UTC (eadf0d9)">Preview</a> | <a …
> Add non-"fully active" document handling guide

- index.bs
Written in a breakout today, this attempts to address #39 and #308.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/320.html" title="Last updated on Sep 15, 2021, 8:13 AM UTC (abd8832)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/320/0e3164c...abd8832.html" title="Last updated on Sep 15, 2021, 8:13 AM UTC (abd8832)">Diff</a>
> Two new principles (actually one existing one recycled) for devices.

- index.bs
Resolves #332.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/334.html" title="Last updated on Sep 15, 2021, 8:36 AM UTC (d1ec778)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/334/e2230d0...d1ec778.html" title="Last updated on Sep 15, 2021, 8:36 AM UTC (d1ec778)">Diff</a>
> Goodbye DOMTimeStamp, hello DOMHighResTimeStamp

- index.bs
(Closes #335)
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/351.html" title="Last updated on Dec 9, 2021, 11:02 AM UTC (cb4cb38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/351/a96703c...cb4cb38.html" title="Last updated on Dec 9, 2021, 11:02 AM UTC (cb4cb38)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/351.html" title="Last updated on Dec 15, 2021, 10:30 AM UTC (1b06615)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/351/a96703c...1b06615.html" title="Last updated on Dec 15, 2021, 10:30 AM UTC (1b06615)">Diff</a>
> Add first pass at principle about designing around third-party tools

- index.bs
Fixes #299.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/306.html" title="Last updated on Apr 16, 2021, 9:22 PM UTC (ebffc6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/306/98bb0d4...ebffc6f.html" title="Last updated on Apr 16, 2021, 9:22 PM UTC (ebffc6f)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/306.html" title="Last updated on Jan 10, 2022, 5:45 PM UTC (900accb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/306/98bb0d4...900accb.html" title="Last updated on Jan 10, 2022, 5:45 PM UTC (900accb)">Diff</a>
> Incorporate Alan Kay's maxim into 'Prefer simple solutions'.

- index.bs
Closes #325
***
<a href="https://pr-preview.s3.amazonaws.com/kenchris/design-principles/pull/356.html" title="Last updated on Jan 27, 2022, 7:34 AM UTC (6f63fe3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/356/51c4da3...kenchris:6f63fe3.html" title="Last updated on Jan 27, 2022, 7:34 AM UTC (6f63fe3)">Diff</a>
> New principle: Where possible APIs should be available in DedicatedWorker

- index.bs
Makes all headings consistently imperative.
Also fixes the 'Other resources' section, which was a subsection of Naming, but I don't think it should have been.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/371.html" title="Last updated on May 17, 2022, 2:42 PM UTC (f91aada)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/371/84bd433...f91aada.html" title="Last updated on May 17, 2022, 2:42 PM UTC (f91aada)">Diff</a>
> Editorial: make headings consistent

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/380.html" title="Last updated on Jul 26, 2022, 9:54 AM UTC (c5bf228)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/380/06e9a85...c5bf228.html" title="Last updated on Jul 26, 2022, 9:54 AM UTC (c5bf228)">Diff</a>
> New principle: Name URL-containing attributes based on their primary purpose. Fixes #278

- index.bs
There needs to be some extra details fleshed out.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/381.html" title="Last updated on Jul 26, 2022, 10:59 AM UTC (253803d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/381/eaf5072...253803d.html" title="Last updated on Jul 26, 2022, 10:59 AM UTC (253803d)">Diff</a>
> Initial commit for #279.

- index.bs
They were added since I last fixed all Bikeshed errors, a couple hours ago.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/384.html" title="Last updated on Jul 26, 2022, 12:32 PM UTC (769d929)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/384/d451ed0...769d929.html" title="Last updated on Jul 26, 2022, 12:32 PM UTC (769d929)">Diff</a>
> Fix newly-introduced Bikeshed errors.

- index.bs
All three examples for «[The abbreviation of "identity"](https://w3ctag.github.io/design-principles/#casing-rules)» link to documents that refer to "identi*fier*" rather than "identi*ty*".
***
<a href="https://pr-preview.s3.amazonaws.com/gibson042/design-principles/pull/414.html" title="Last updated on Jan 6, 2023, 4:36 PM UTC (1bd0be4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/414/c5e4fea...gibson042:1bd0be4.html" title="Last updated on Jan 6, 2023, 4:36 PM UTC (1bd0be4)">Diff</a>
> Clarify that "id" abbreviates "identifier"

- index.bs
Fixes #360.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/404.html" title="Last updated on Feb 7, 2023, 1:35 AM UTC (f81761f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/404/e81cae6...f81761f.html" title="Last updated on Feb 7, 2023, 1:35 AM UTC (f81761f)">Diff</a>
> New principle: Some APIs should only be exposed to dedicated workers

- index.bs
As observed in failure of the [latest deploy job](https://github.com/w3ctag/design-principles/actions/runs/3795480809/jobs/6454644278):
> ```
> bikeshed --die-on=fatal spec index.bs build/index.html
> LINT: Your document appears to use spaces to indent, but line 795 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 796 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 797 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 798 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 799 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 803 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 804 starts with …
```
> Fix lint issues

- index.bs
Some things changed between opening #413 and merging it, and the [latest deploy job](https://github.com/w3ctag/design-principles/actions/runs/4119796701/jobs/7113862049) still has fatal errors.
> ```
> bikeshed --die-on=fatal spec index.bs build/index.html
> LINT: Your document appears to use spaces to indent, but line 795 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 796 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 797 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 798 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 799 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 803 starts with tabs.
> LINT: Your document …
```
> Fix more lint issues

- index.bs
Resolves #402.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/417.html" title="Last updated on Feb 9, 2023, 1:37 AM UTC (bc34ecd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/417/9a45512...bc34ecd.html" title="Last updated on Feb 9, 2023, 1:37 AM UTC (bc34ecd)">Diff</a>
> Add new principle for sync() vs async().

- index.bs
@chrishtr wanted to document guidance on this situation, and I thought it would make sense to put it here rather than in a Chromium-specific place. Let me know if you want different guidance or think this isn't the right place after all.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/357.html#devices-platforms" title="Last updated on Apr 6, 2023, 6:36 AM UTC (479f53f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/357/e81cae6...jyasskin:479f53f.html" title="Last updated on Apr 6, 2023, 6:36 AM UTC (479f53f)">Diff</a>
> Describe what to do when a feature is temporarily only available on some platforms.

- .github/workflows/deploy.yml
- index.bs
tabs -> spaces
Only the last commit is significant here, don't know why other commits are listed
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/405.html" title="Last updated on Dec 7, 2022, 5:00 PM UTC (da6a721)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/405/44c0066...da6a721.html" title="Last updated on Dec 7, 2022, 5:00 PM UTC (da6a721)">Diff</a>
> Fixing markup

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/design-principles/pull/439.html" title="Last updated on May 8, 2023, 4:09 PM UTC (af46d7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/439/0559332...jan-ivar:af46d7f.html" title="Last updated on May 8, 2023, 4:09 PM UTC (af46d7f)">Diff</a>
> Fix link to live-vs-static

- index.bs
Also includes some bikeshed indentation error fixes.
***
<a href="https://pr-preview.s3.amazonaws.com/wolenetz/design-principles/pull/408.html" title="Last updated on Apr 20, 2023, 2:26 AM UTC (2d154fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/408/69b2ff0...wolenetz:2d154fd.html" title="Last updated on Apr 20, 2023, 2:26 AM UTC (2d154fd)">Diff</a>
> Warn against getter throwing exception since it is a side effect

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jakearchibald/design-principles/pull/460.html" title="Last updated on Apr 1, 2024, 8:51 PM UTC (7b95818)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/460/7fe598f...jakearchibald:7b95818.html" title="Last updated on Apr 1, 2024, 8:51 PM UTC (7b95818)">Diff</a>
> More detail on why events should fire before promises

- index.bs
Fixes https://github.com/w3ctag/design-principles/issues/463.
***
<a href="https://pr-preview.s3.amazonaws.com/bakkot/design-principles/pull/480.html" title="Last updated on Apr 3, 2024, 1:35 AM UTC (ad59b8b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/480/222226d...bakkot:ad59b8b.html" title="Last updated on Apr 3, 2024, 1:35 AM UTC (ad59b8b)">Diff</a>
> New principle: vend byte arrays as Uint8Arrays

- index.bs
Bikeshed complained about broken links, so I fixed those. Trailing whitespace is always unnecessary.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/design-principles/pull/489.html" title="Last updated on Apr 4, 2024, 9:47 PM UTC (30c9222)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/489/ff46d8f...martinthomson:30c9222.html" title="Last updated on Apr 4, 2024, 9:47 PM UTC (30c9222)">Diff</a>
> Fix some nits

- index.bs
HTML vs. IDL
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/design-principles/pull/485.html" title="Last updated on Jun 3, 2024, 3:57 PM UTC (4775ff0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/485/222226d...martinthomson:4775ff0.html" title="Last updated on Jun 3, 2024, 3:57 PM UTC (4775ff0)">Diff</a>
> Attempt to split attribute by type

- index.bs
The new features text seemed to have all sorts of duplicate text... not sure why?
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/design-principles/pull/494.html" title="Last updated on May 21, 2024, 5:11 AM UTC (009d364)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/494/ca6bfaf...marcoscaceres:009d364.html" title="Last updated on May 21, 2024, 5:11 AM UTC (009d364)">Diff</a>
> fix duplicative text in new-features

- index.bs
Spotted a couple typos.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/design-principles/pull/508.html" title="Last updated on Aug 2, 2024, 5:33 PM UTC (1b48d9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/508/55a06e0...jan-ivar:1b48d9a.html" title="Last updated on Aug 2, 2024, 5:33 PM UTC (1b48d9a)">Diff</a>
> Fix typos.

- index.bs
The existing one is dated.  Most of that advice is now in RFC 9205.
There is also more general advice in that document, so the guidance here gets more complex as a result.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/design-principles/pull/487.html" title="Last updated on Apr 5, 2024, 10:31 AM UTC (7fc9d5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/487/12d02ab...martinthomson:7fc9d5b.html" title="Last updated on Apr 5, 2024, 10:31 AM UTC (7fc9d5b)">Diff</a>
> Update principle on HTTP usage

- index.bs
WIP
Closes #298.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/504.html" title="Last updated on Aug 21, 2024, 8:01 AM UTC (9620dfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/504/55a06e0...9620dfc.html" title="Last updated on Aug 21, 2024, 8:01 AM UTC (9620dfc)">Diff</a>
> Prefer composition

- index.bs
Here's an initial draft for text on exposing interfaces everywhere. It's similar to the text I wrote in #509 and the examples I gave there.
Closes: #509
***
<a href="https://pr-preview.s3.amazonaws.com/ptomato/w3ctag-design-principles/pull/510.html" title="Last updated on Oct 4, 2024, 1:02 AM UTC (0777bc0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/510/55a06e0...ptomato:0777bc0.html" title="Last updated on Oct 4, 2024, 1:02 AM UTC (0777bc0)">Diff</a>
> New text for guidance on exposing interfaces everywhere

- index.bs
The first fix is fine.  The next two...
A backslash convinces BS that `[HTTP](link)` is a link.
Changing `&` in a link to `&amp;` convinces BS that there are ampersands in the link.
These last two are bugs in BS.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/520.html" title="Last updated on Dec 4, 2024, 10:09 AM UTC (5676694)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/520/6f3fb06...5676694.html" title="Last updated on Dec 4, 2024, 10:09 AM UTC (5676694)">Diff</a>
> These are abominable

- index.bs
As noted in #437, simple advice to treat absence as equivalent to being passed `undefined` is a mistake.  This advice only really applies to Boolean arguments.
We discussed and concluded that string and number arguments have no sensible default that we could recommend.  Booleans do.
Closes #437.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/518.html" title="Last updated on Dec 4, 2024, 9:56 AM UTC (1192e94)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/518/6f3fb06...1192e94.html" title="Last updated on Dec 4, 2024, 9:56 AM UTC (1192e94)">Diff</a>
> Correct bad advice on undefined conversion

- index.bs
This is related to #454
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/517.html#idl-string-types" title="Last updated on Dec 4, 2024, 1:32 PM UTC (7908ef2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/517/fbf6370...7908ef2.html" title="Last updated on Dec 4, 2024, 1:32 PM UTC (7908ef2)">Diff</a>
> adding a note to ensure consistency with  'Defining string' section of [international-spec]

- index.bs
This rewords some of the text from #470 to address a latent concern.
It also switches from "id" to "identifier".
Closes #479.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/525.html" title="Last updated on Dec 4, 2024, 1:54 PM UTC (8fcc4c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/525/fbf6370...8fcc4c8.html" title="Last updated on Dec 4, 2024, 1:54 PM UTC (8fcc4c8)">Diff</a>
> Device access permissions and fingerprinting

- index.bs
Draft
Closes #453.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/505.html" title="Last updated on Dec 4, 2024, 3:55 PM UTC (f1cfef8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/505/55a06e0...f1cfef8.html" title="Last updated on Dec 4, 2024, 3:55 PM UTC (f1cfef8)">Diff</a>
> Text formats are for people

- index.bs
I'm sure that we could say more, but I think that this is enough.
Closes #370.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/502.html" title="Last updated on Dec 4, 2024, 4:10 PM UTC (c0567ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/502/efad741...c0567ab.html" title="Last updated on Dec 4, 2024, 4:10 PM UTC (c0567ab)">Diff</a>
> Establish a rule about element overloading

- index.bs
The previous form of [this sentence](https://w3ctag.github.io/design-principles/#usecase-oriented-apis) was incomplete in some way.
I've made it shorter and maybe more grammatical.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/design-principles/pull/540.html" title="Last updated on Dec 10, 2024, 2:57 AM UTC (c67e619)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/540/e9fd206...martinthomson:c67e619.html" title="Last updated on Dec 10, 2024, 2:57 AM UTC (c67e619)">Diff</a>
> Correct grammatical error

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/534.html#using-http" title="Last updated on Dec 4, 2024, 4:37 PM UTC (bed9eba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/534/e9fd206...jyasskin:bed9eba.html" title="Last updated on Dec 4, 2024, 4:37 PM UTC (bed9eba)">Diff</a>
> Use more semantic references to HTTP RFCs.

- index.bs
* "While an event loop is running" wasn't the right period to limit changes.
* We have a list of exceptions to this principle.
This is meant to fix #456; @jakearchibald, can you check it? Thank you for the text!
I think this also supersedes #496. @jan-ivar, have I caught everything you meant to say there?
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/536.html#js-rtc" title="Last updated on Dec 17, 2024, 10:26 PM UTC (21262c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/536/6c1568b...jyasskin:21262c9.html" title="Last updated on Dec 17, 2024, 10:26 PM UTC (21262c9)">Diff</a>
> Improve the run-to-completion principle.

- index.bs
Fixes #303.
I'm happy to add more links to useful guidance either in this PR or in future ones.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/542.html#specs-include-guidance" title="Last updated on Dec 17, 2024, 7:22 PM UTC (f980d22)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/542/6c1568b...jyasskin:f980d22.html" title="Last updated on Dec 17, 2024, 7:22 PM UTC (f980d22)">Diff</a>
> Add a section about looking for guidance in other specs.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/547.html" title="Last updated on Jan 15, 2025, 1:18 AM UTC (0379b87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/547/f2f2641...jyasskin:0379b87.html" title="Last updated on Jan 15, 2025, 1:18 AM UTC (0379b87)">Diff</a>
> Fix markup mistakes caught by bikeshed's new parser.

- index.bs
I found that I needed to redo the whole section here. Changing the focus seemed better than adding text. This is more text, but not a lot more.
Future-proofing is one motivation, but it's not the real motivation for these recommendations.
I also found the key event example to be spectacularly non-compelling. It even made me think that it is almost a bad example. Key events can be synthesized by speech recognition tools in some cases.
To that end, I chose an example that I'm more familiar with.
Closes #507.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/design-principles/pull/550.html" title="Last updated on Jan 30, 2025, 4:45 AM UTC (7611b68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/550/0379b87...martinthomson:7611b68.html" …
> Use names that describe purpose

- index.bs
@ylafon, the removed "See" bit comes from your comment in #379, so feel free to object.
I see we have some other proposals to add web-specific HTTP guidance. This PR doesn't preclude adding back a less-redundant section on this space. :)
Fixes #545.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/546.html#specs-include-guidance" title="Last updated on Jan 15, 2025, 1:28 AM UTC (b8e548c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/546/0379b87...jyasskin:b8e548c.html" title="Last updated on Jan 15, 2025, 1:28 AM UTC (b8e548c)">Diff</a>
> Merge the HTTP guidance into the "consult other specs" section.

- .github/workflows/deploy.yml
- README.md
- index.bs
This should go in after
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/549.html" title="Last updated on Feb 25, 2025, 9:27 PM UTC (e3fed99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/549/0975d2b...jyasskin:e3fed99.html" title="Last updated on Feb 25, 2025, 9:27 PM UTC (e3fed99)">Diff</a>
> Auto-publish the Design Principles.

- index.bs
Adds examples and tightens things up.
Adds a mention that WebIDL enums only take string values.
One thing that jumped out here was that WebIDL permits the use of numeric/integer constants.  I searched all of the Firefox codebase and I didn't find a single useful instance where a numeric constant made sense.
My operating theory before starting was that there might be some case where developers might be exposed to a number in contexts outside of the web, which might mean that using a numeric constant in the platform made sense.
The one example of that we have is KeyboardEvent.keyCode, which might have made sense if it exposed the Unicode codepoint of a key.  That, however, is solidly deprecated in favor of a much better API.
Every other instance was a bad example.
Closes #427.
***
<a …
> Clarify the strings for enums/constants principle

- index.bs
Disambiguate #blockwidth reference, leading to error in bikeshed
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/566.html" title="Last updated on Mar 25, 2025, 8:27 AM UTC (374f06f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/566/8039864...374f06f.html" title="Last updated on Mar 25, 2025, 8:27 AM UTC (374f06f)">Diff</a>
> fix bikeshed error (disambiguate #blockwidth reference)

- index.bs
Bikeshed noticed that one of our links into the Privacy Principles was
broken, so I reworded the link to be more precise and point at an
existing section.
We deleted the old `#threats` section, which was a copy of the list from https://datatracker.ietf.org/doc/html/rfc6973#section-5. I think the relevant one here, though is just that the information might be sensitive.
This also uses the wrong ID for the target section due to https://github.com/speced/respec/issues/4947 and https://github.com/w3c/reffy/issues/1824. When the respec bug is fixed, this should become `PRIVACY-PRINCIPLES#hl-sensitive-information`.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/design-principles/pull/571.html" title="Last updated on Apr 29, 2025, 6:33 PM UTC (aa3fd36)">Preview</a> | <a …
> Fix Bikeshed errors.

- index.bs
As this will include a bunch of useful guidance in working with HTTP in specifications that we don't need to maintain.
Closes #422.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/587.html" title="Last updated on Sep 18, 2025, 2:59 AM UTC (b241bf5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/587/c757c94...b241bf5.html" title="Last updated on Sep 18, 2025, 2:59 AM UTC (b241bf5)">Diff</a>
> Reference HTTP WG style guide

- index.bs
There was also discussion of linking to WCAG's definition of AT, which is good, but is labelled as '(as used in this document)' and the reason for this (having tried some digital excavation) is not clear, so I will leave that to a separate PR.
Thus this partly addresses #529
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/589.html" title="Last updated on Sep 18, 2025, 3:10 AM UTC (edd57a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/589/c757c94...edd57a9.html" title="Last updated on Sep 18, 2025, 3:10 AM UTC (edd57a9)">Diff</a>
> Remove notion of asking for consent to reveal AT use

- index.bs
fix example by linking to the proper IDL definitions, fixes #573
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/pull/591.html" title="Last updated on Sep 18, 2025, 3:58 AM UTC (cff1b14)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/591/c757c94...cff1b14.html" title="Last updated on Sep 18, 2025, 3:58 AM UTC (cff1b14)">Diff</a>
> Fix example in Keep attributes in sync
